

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DBCaseSystem_KokovinMedvedevStartsev
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ModelMetaDataContainer : DbContext
{
    public ModelMetaDataContainer()
        : base("name=ModelMetaDataContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Table> TableSet { get; set; }

    public virtual DbSet<Relation> RelationSet { get; set; }

    public virtual DbSet<Attribute> AttributeSet { get; set; }

    public virtual DbSet<Query> QuerySet { get; set; }

    public virtual DbSet<Database> DatabaseSet { get; set; }

    public virtual DbSet<QueryOutput> QueryOutputSet { get; set; }

    public virtual DbSet<QueryObject> QueryObjectSet { get; set; }

}

}

