
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DBCaseSystem_KokovinMedvedevStartsev
{

using System;
    using System.Collections.Generic;
    
public partial class Query
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Query()
    {

        this.QueryOutput = new HashSet<QueryOutput>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string QueryText { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<QueryOutput> QueryOutput { get; set; }

    public virtual QueryObject QueryObject { get; set; }

}

}
