//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCaseSystem_KokovinMedvedevStartsev
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class SQLQuery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SQLQuery()
        {
            this.QueryObject = new HashSet<QueryObject>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QueryObject> QueryObject { get; set; }
        public virtual QueryObject QueryObject1 { get; set; }
    }
}
